name: 'My First GitHub Actions'

on: 
  push: 
    branches:
      - main
    tags: 
      - 'v*'

  pull_request:
    branches:
      - main
    
jobs:
  build:
    name: 'Build App'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      
      - name: Restore NuGet pakages
        shell: bash
        run: |
          dotnet restore ./api

      - name: Create artifact
        shell: bash
        run: |
          donet publish ./api -c Release -o ./api/bin/published
      
      - name: Upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: apiapp
          path: api/bin/published